#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
Run single XPath expression on the given document and display the results

Usage:
    xp <filename> <path>

Arguments:
    <filename>  The name of the file to query with XPath
    <path>      The path to query the document with
"""

from docopt import docopt
import lxml
import lxml.html


def main(path, doc):
    values = doc.xpath(path)
    for idx, value in enumerate(values):
        if isinstance(value, lxml.html.HtmlElement):
            print idx
            print 'elem.text_content:', value.text_content()
            print 'elem.tail: "%s"' % (value.tail.strip(),)
        else:
            print idx
            print value
    print


if __name__ == '__main__':
    args = docopt(__doc__)
    filename = args['<filename>']
    path = args['<path>']

    doc = lxml.html.fromstring(open(filename, 'r').read())
    main(path, doc)
